### ISSUE TITLE
protected live no longer work(?)

### ISSUE THREAD

**Issue by PeanutAria** [Spicadox/auto-twitcasting#1]
for some reason protected live download doesn't work.

the problem started a week a go if i'm not mistaken. everything was fine before and i never change my setting.
i've tried updating yt-dlp, ffmpeg to the latest version but nothing works.

i'm able to screenshot the cmd before it was gone. during this time, i had only one line of password in the password txt file and it was the password for the live that i'm trying to download
![2022-12-27 19_28_44-2022-12-27_19-09-12 mp4_-_mpv](https://user-images.githubusercontent.com/121492287/209660191-c00d90bb-9d79-4a6e-9836-afc21ffb6173.png)

EDIT: strike the words below since it doesn't works when i tried it again today. same thing happened as above after i entered the live stream before restarting the script

~~but for some reason if i entered the live stream on my browser and restart the script, the download start fine but since it open multiple cmd, all the cmd started download like a normal live.~~

~~i.e. if i had 3 password line, it should open 4 cmd (1 without password, 3 with password from txt file), all 4 will start download instead of only one with the correct password.~~

tried to explain it my best. sorry english is not my first language

**Comment by Spicadox** [comment]
This appears to be an issue with yt-dlp and I've raised an [issue](https://github.com/yt-dlp/yt-dlp/issues/5888#issue-1512180283) for it as it appears that at this moment yt-dlp can not download protected videos using passwords or cookies.

I'll address your concerns despite you striking it out, but I just coded it lazily so that means as of now you'll be seeing multiple consoles opening up at once depending on how many passwords are in the file plus an extra console for an extra password automatically adding the date to the password list. 
This is expected, but I had not considered the scenario where you would manually input the password before the downloaded started which I guess will result in multiple instances of the same download(though that kinda defeats the purpose of the script cause at that point you might as well just manually start downloading using yt-dlp ;P). To combat this and when I have time I could add checks to ensure the video is properly unlocked so you won't have a bunch of consoles popping up at once.

No worries thanks for bringing this up!

**Comment by PeanutAria** [comment]
lucky me had someone on my list currently streaming with password. tried the yt-dlp patch and it works. thank you 😄 

EDIT:
read the yt-dlp issue thread again and i did update my cookies txt file when the problem started because i thought it had something to do with it. i guess that explained why i doesn't work with another live

**Comment by Spicadox** [comment]
Patch has been merged and should be fixed in the latest yt-dlp commit
