### ISSUE TITLE
Auto-renew bearer token using SNS login ID

### ISSUE THREAD

**Issue by PeanutAria** [Spicadox/auto-twitcasting#2]
Because of the change in Twitter API, TwitCasting add a new login method for those who created TwitCasting account using SNS account
https://twitter.com/twitcasting_jp/status/1621490729372782592
https://twitcasting.tv/helpcenter.php?pid=6039

And since my token just expired, I wanted to try the auto-renew option, but failed because the login page is different. It uses https://twitcasting.tv/indexpasswordlogin.php instead of https://twitcasting.tv/indexcaslogin.php

![2023-02-04 00_24_34-TwitCasting_Account_Login_-_TwitCasting_—_Mozilla_](https://user-images.githubusercontent.com/121492287/216654910-8f19f749-9c14-40ad-ad2b-610bbf099def.png)
![2023-02-04 00_25_05-SNS_Login_with_login_password_-_TwitCasting_—_Mozi](https://user-images.githubusercontent.com/121492287/216654989-d90064f9-f31d-4252-802a-55200eadf90d.png)

**Comment by Spicadox** [comment]
Hey,
Just pushed the newest changes([cf9a3e8](https://github.com/Spicadox/auto-twitcasting/commit/cf9a3e87ea957e5816db05d83efc5b07a2bde1dc)) so token renewal isn't needed, thus this issue will not appear again. Requests are now sent using `Client ID` and `Client Secret` which does not require renewal. All you would need to do is specify `Client ID` and `Client Secret` in your `const.py` file.

**Comment by PeanutAria** [comment]
Tested and it works. Thank you 😊 

btw, I had to remove the `.mkv` from line 452 in `index.py` https://github.com/Spicadox/auto-twitcasting/blob/57ba572748a0cdbf1a5d041bdb19ec35669c7767/index.py#L452 or the downloaded file ended up with double `.mkv` i.e `Recent Live.mkv.mkv` since on line 451 it already specified the file extension https://github.com/Spicadox/auto-twitcasting/blob/57ba572748a0cdbf1a5d041bdb19ec35669c7767/index.py#L451

Upon further testing, I found out that remove either `.mkv` works, either on line 451 or 452. But, removing both will result in yt-dlp `File has already been downloaded`

Also, I don't know why, but I can't make the new added 'check_file' (line 25 - 36) work.
https://github.com/Spicadox/auto-twitcasting/blob/57ba572748a0cdbf1a5d041bdb19ec35669c7767/index.py#L25-L36
It still overwrites the existing file.

BTW, if you already read this, please give me some time to give you some explanation for the `check_file`

**Comment by Spicadox** [comment]
Whoops, just fixed it. I've been using this function in another script and haven't had any issues.

**Comment by PeanutAria** [comment]
I like to keep all the downloaded file in 1 folder, so I changed line 451 & 452 to
```
file_name = check_file(f'[{screen_id}][{live_date}] {live_title} ({live_id}).mkv', output_path)
output = f'{output_path}/{file_name}'
```
and also line 25 - 27 to
```
def check_file(file_name, output_path):
    try:
        if os.path.isfile(f'{output_path}\\{file_name}'):
```

but it still overwrites the existing file. Am I missing something?

**Comment by Spicadox** [comment]
The issue is because I'm using a specific regex expression(line 29 above) to match for this specific filename format: `{live_date} - {live_title} ({live_id}).mkv`

Now, changing the file format to `[{screen_id}][{live_date}] {live_title} ({live_id}).mkv` will require changing not only the regex expression but also rebuilding the filename as I decided to add uniqueness to the filename by appending the time to the date instead of incrementally appending a number to the end of the filename.

I pushed new changes and removed regex check(I was trying to do something hence why I decided to use regex but it probably wasn't worth the effort given it's just a fast and dirty script I cooked up on the spot 😅). You can just change line 24 and 28 to match the file format you like.
https://github.com/Spicadox/auto-twitcasting/blob/9592d1b9ffea5009b85998e01f37905ab831ab95/index.py#L23-L32

**Comment by PeanutAria** [comment]
Thank you so much 😄😊
